#!/usr/bin/env bash
# =============================================================
# install.sh / tacacs-migrate.sh — Installer & manager
#                                  for TACACS+ migration playbook
# =============================================================
# Two operating modes detected automatically:
#
#   SOURCE mode  — run from the source directory (roles/ present)
#                  Commands: install, status, help
#
#   INSTALLED mode — run from the installed playbook directory
#                    (.installed marker present, or copied as tacacs-migrate.sh)
#                    Commands: configure, configure-hosts, configure-vault,
#                              configure-vault-password, run, status,
#                              uninstall, help
#
# On install, this script copies itself to INSTALL_DIR/tacacs-migrate.sh
# so the user can manage the deployment from there without the source repo.
# =============================================================
set -euo pipefail

# ---------- colours ------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

# ---------- paths --------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
PLAYBOOK_NAME="tacacs-migrate"
VAULT_FILE_REL="playbook/vars/vault.yml"

# ---------- helpers ------------------------------------------
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()      { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()     { error "$*"; exit 1; }
header()  { echo -e "\n${BOLD}=== $* ===${NC}"; }

prompt() {
    local var="$1" desc="$2" default="${3:-}"
    local input
    if [[ -n "$default" ]]; then
        echo -ne "${BOLD}${desc}${NC} [${default}]: "
    else
        echo -ne "${BOLD}${desc}${NC}: "
    fi
    read -r input || { echo; _on_interrupt; }
    [[ -z "$input" && -n "$default" ]] && input="$default"
    printf -v "$var" '%s' "$input"
}

prompt_secret() {
    local var="$1" desc="$2"
    local input
    echo -ne "${BOLD}${desc}${NC} (hidden): "
    read -rs input || true
    echo
    printf -v "$var" '%s' "$input"
}

confirm() {
    echo -ne "${BOLD}${1}${NC} [y/N]: "
    local r
    read -r r || { echo; _on_interrupt; }
    if [[ "$r" =~ ^[Yy]$ ]]; then return 0; else return 1; fi
}

# ---------- mode detection -----------------------------------
detect_mode() {
    if [[ -f "${SCRIPT_DIR}/.installed" ]]; then
        echo "installed"
    elif [[ -d "${SCRIPT_DIR}/roles" ]]; then
        echo "source"
    else
        echo "installed"   # fallback: assume deployed context
    fi
}

detect_default_location() {
    if [[ $EUID -eq 0 ]]; then
        echo "/etc/ansible/playbooks/${PLAYBOOK_NAME}"
    else
        echo "${HOME}/.ansible/playbooks/${PLAYBOOK_NAME}"
    fi
}

MODE="$(detect_mode)"

if [[ "$MODE" == "installed" ]]; then
    INSTALL_DIR="${SCRIPT_DIR}"
else
    INSTALL_DIR="${INSTALL_DIR:-$(detect_default_location)}"
fi

# ---------- path helpers -------------------------------------
vars_file()  { echo "${INSTALL_DIR}/vars.env"; }
vault_file() { echo "${INSTALL_DIR}/${VAULT_FILE_REL}"; }

# ---------- vault security — cleanup unencrypted file --------
_VAULT_GUARD=""

_vault_cleanup() {
    if [[ -n "$_VAULT_GUARD" && -f "$_VAULT_GUARD" ]]; then
        if ! head -1 "$_VAULT_GUARD" 2>/dev/null | grep -q '^\$ANSIBLE_VAULT'; then
            warn "Removing unencrypted vault.yml (interrupted operation)"
            if command -v shred &>/dev/null; then
                shred -uz "$_VAULT_GUARD" 2>/dev/null || rm -f "$_VAULT_GUARD"
            else
                rm -f "$_VAULT_GUARD"
            fi
        fi
    fi
}

_on_interrupt() {
    echo
    info "Interrupted."
    exit 130
}

trap '_vault_cleanup' EXIT
trap '_on_interrupt'  INT TERM HUP

# ---------- load / save vars ---------------------------------
load_vars() {
    local vf; vf="$(vars_file)"
    [[ -f "$vf" ]] && source "$vf" || true  # shellcheck disable=SC1090
}

save_vars() {
    local vf; vf="$(vars_file)"
    cat > "$vf" <<EOF
# tacacs-migrate configuration — generated by ${SCRIPT_NAME}
# Do not commit to git

# --- Vault ---
VAULT_PASSWORD_FILE="${VAULT_PASSWORD_FILE:-}"
EOF
    chmod 600 "$vf"
    ok "Configuration saved: $vf"
}

# ---------- dependency check ---------------------------------
check_dependencies() {
    header "Checking dependencies"
    local all_ok=true

    for cmd_desc in \
        "ansible-playbook:ansible-playbook (apt install ansible)" \
        "ansible-vault:ansible-vault (part of ansible)" \
        "python3:python3 (apt install python3)" \
        "openssl:openssl (apt install openssl)"; do
        local cmd="${cmd_desc%%:*}"
        local desc="${cmd_desc#*:}"
        if command -v "$cmd" &>/dev/null; then
            ok "${cmd}: found"
        else
            error "${cmd} not found — install: ${desc}"
            all_ok=false
        fi
    done

    if ansible-galaxy collection list 2>/dev/null | grep -q "cisco.ios"; then
        ok "cisco.ios: present"
    else
        warn "cisco.ios not found — installing..."
        if ansible-galaxy collection install cisco.ios; then
            ok "cisco.ios: installed"
        else
            error "Failed to install cisco.ios"
            all_ok=false
        fi
    fi

    # ssh-broker check — warning only, not a hard requirement
    local broker_ok=false
    if [[ -f "/opt/ssh-broker/.installed" ]]; then
        ok "ssh-broker: installed at /opt/ssh-broker"
        broker_ok=true
    elif command -v curl &>/dev/null; then
        local _br_url="${BROKER_URL:-http://127.0.0.1:8765}"
        if curl -sf --max-time 2 "${_br_url}/health" &>/dev/null; then
            ok "ssh-broker: running at ${_br_url}"
            broker_ok=true
        fi
    fi
    if [[ "$broker_ok" == false ]]; then
        warn "ssh-broker not detected — safety session rollback will not be available."
        warn "Install ssh-broker before running migration, or configure broker settings later:"
        warn "  $0 configure-broker"
    fi

    [[ "$all_ok" == true ]]
}

# =============================================================
# VAULT PASSWORD
# =============================================================

find_vault_password_files() {
    local candidates=()

    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        candidates+=("${VAULT_PASSWORD_FILE}")
    fi

    local cfgs=(
        "${INSTALL_DIR}/playbook/ansible.cfg"
        "${HOME}/.ansible.cfg"
        "/etc/ansible/ansible.cfg"
    )
    for cfg in "${cfgs[@]}"; do
        if [[ -f "$cfg" ]]; then
            local cfg_vp
            cfg_vp="$(grep -E '^\s*vault_password_file\s*=' "$cfg" 2>/dev/null \
                      | sed 's/.*=\s*//' | tr -d ' \t' | head -1 || true)"
            cfg_vp="${cfg_vp/#\~/$HOME}"
            [[ -n "$cfg_vp" && -f "$cfg_vp" ]] && candidates+=("$cfg_vp")
        fi
    done

    local common=(
        "${HOME}/.ansible/vault_pass"
        "${HOME}/.ansible/vault_password"
        "${HOME}/.vault_pass"
        "${HOME}/.vault_password"
        "/etc/ansible/vault/.vault_pass"
        "/etc/ansible/vault/vault_pass"
    )
    for f in "${common[@]}"; do
        [[ -f "$f" ]] && candidates+=("$f")
    done

    local seen=()
    for f in "${candidates[@]:-}"; do
        local dup=false
        for s in "${seen[@]:-}"; do [[ "$s" == "$f" ]] && dup=true && break; done
        [[ "$dup" == false ]] && seen+=("$f")
    done

    printf '%s\n' "${seen[@]:-}"
}

configure_vault_password() {
    header "Vault password"
    info "The vault password protects local_pass, local_enable, tacacs_key, etc."
    echo

    VAULT_RAW_PASSWORD=""

    local candidates=()
    while IFS= read -r line; do
        [[ -n "$line" ]] && candidates+=("$line")
    done < <(find_vault_password_files)

    local options=()
    local i=1

    if [[ ${#candidates[@]} -gt 0 ]]; then
        for f in "${candidates[@]}"; do
            echo -e "  ${BOLD}${i})${NC} Use existing file: ${CYAN}${f}${NC}"
            options+=("$f")
            i=$(( i + 1 ))
        done
        echo
    fi

    echo -e "  ${BOLD}${i})${NC} Specify a different file path"
    options+=("__custom_path__")
    i=$(( i + 1 ))
    echo -e "  ${BOLD}${i})${NC} Enter password manually (offer to save to file)"
    options+=("__manual__")
    local max=$i

    echo
    local choice idx selected
    while true; do
        echo -ne "Choice [1-${max}]: "
        read -r choice || _on_interrupt
        if [[ "$choice" =~ ^[0-9]+$ ]]; then
            idx=$(( choice - 1 ))
            if [[ $idx -ge 0 && $idx -lt ${#options[@]} ]]; then break; fi
        fi
        warn "Please enter a number between 1 and ${max}."
    done

    selected="${options[$idx]}"

    case "$selected" in
        __custom_path__)
            local default_path="${HOME}/.ansible/vault_pass"
            prompt VAULT_PASSWORD_FILE "Path to vault password file" "$default_path"
            VAULT_PASSWORD_FILE="${VAULT_PASSWORD_FILE/#\~/$HOME}"
            if [[ ! -f "$VAULT_PASSWORD_FILE" ]]; then
                warn "File not found: ${VAULT_PASSWORD_FILE}"
                warn "Ensure the file exists before running the playbook."
            else
                ok "Will use: ${VAULT_PASSWORD_FILE}"
            fi
            ;;
        __manual__)
            _vault_password_manual
            ;;
        *)
            [[ -f "$selected" ]] || die "Vault password file not found: '${selected}'"
            VAULT_PASSWORD_FILE="$selected"
            ok "Will use: ${VAULT_PASSWORD_FILE}"
            ;;
    esac
}

_vault_password_manual() {
    local pw pw2
    while true; do
        prompt_secret pw "Enter vault password"
        [[ -z "$pw" ]] && { warn "Password cannot be empty."; continue; }
        prompt_secret pw2 "Confirm vault password"
        [[ "$pw" == "$pw2" ]] && break
        warn "Passwords do not match. Try again."
    done
    VAULT_RAW_PASSWORD="$pw"

    echo
    warn "IMPORTANT: If you lose the vault password, secrets cannot be recovered."
    echo
    if confirm "Save password to a file for future use?"; then
        local default_path="${HOME}/.ansible/vault_pass"
        prompt VAULT_PASSWORD_FILE "Path to save password file" "$default_path"
        VAULT_PASSWORD_FILE="${VAULT_PASSWORD_FILE/#\~/$HOME}"
        mkdir -p "$(dirname "$VAULT_PASSWORD_FILE")"
        printf '%s' "$pw" > "$VAULT_PASSWORD_FILE"
        chmod 600 "$VAULT_PASSWORD_FILE"
        ok "Password saved: ${VAULT_PASSWORD_FILE}"
        warn "Back up this file to a password manager."
        VAULT_RAW_PASSWORD=""
    else
        VAULT_PASSWORD_FILE=""
        warn "No file saved — you will be prompted for the password on every run."
    fi
}

vault_args() {
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        printf '%s\n' "--vault-id" "default@${VAULT_PASSWORD_FILE}"
    elif [[ -n "${VAULT_RAW_PASSWORD:-}" ]]; then
        printf '%s\n' "--vault-id" "default@/dev/stdin"
    else
        printf '%s\n' "--ask-vault-pass"
    fi
}

vault_stdin_pipe() {
    if [[ -n "${VAULT_RAW_PASSWORD:-}" ]]; then
        printf '%s' "${VAULT_RAW_PASSWORD}"
    fi
}

# =============================================================
# TACACS+ SERVERS CONFIGURATION
# =============================================================

configure_servers() {
    header "Configure TACACS+ servers"
    info "Enter primary and (optionally) secondary TACACS+ server."
    info "Leave secondary empty to use a single server."
    echo

    prompt TACACS_SERVER_PRIMARY "Primary TACACS+ server IP" "${TACACS_SERVER_PRIMARY:-}"
    if [[ -z "${TACACS_SERVER_PRIMARY:-}" ]]; then die "Aborted: primary TACACS+ server IP is required and cannot be empty."; fi

    echo
    prompt TACACS_SERVER_SECONDARY "Secondary TACACS+ server IP (leave empty for single server)" \
        "${TACACS_SERVER_SECONDARY:-}"

    if [[ -n "${TACACS_SERVER_SECONDARY:-}" ]]; then
        ok "Two servers configured: ${TACACS_SERVER_PRIMARY}, ${TACACS_SERVER_SECONDARY}"
    else
        ok "Single server configured: ${TACACS_SERVER_PRIMARY}"
    fi

    echo
    echo -e "${BOLD}-- TACACS+ shared key --${NC}"
    prompt_secret TACACS_KEY "TACACS+ shared key (shared secret configured on your TACACS+ servers)"
    if [[ -z "${TACACS_KEY:-}" ]]; then die "Aborted: TACACS+ shared key is required and cannot be empty."; fi
}

# =============================================================
# SWITCH CREDENTIALS
# =============================================================

configure_switch_credentials() {
    header "Switch credentials (local auth)"
    info "These credentials are used to connect to switches for migration."
    info "They must be LOCAL admin credentials (not TACACS+)."
    echo

    prompt LOCAL_USER   "Switch local username"        "${LOCAL_USER:-admin}"
    prompt_secret LOCAL_PASS         "Switch local password"
    prompt_secret LOCAL_ENABLE       "Switch enable secret (level 15, leave empty if not needed)"

    echo
    info "The admin user will be recreated with privilege 15 and an encrypted secret during preflight."
    prompt_secret LOCAL_ADMIN_SECRET "Switch admin user secret (type 9, for 'username admin privilege 15 secret')"
    if [[ -z "${LOCAL_ADMIN_SECRET:-}" ]]; then die "Aborted: admin secret is required and cannot be empty. It is used during preflight to ensure the admin user has privilege 15."; fi

    ok "Switch credentials configured for user: ${LOCAL_USER}"
}

# =============================================================
# TACACS+ TEST USER
# =============================================================

configure_test_user() {
    header "TACACS+ test user"
    info "A TACACS+ user to verify authentication after migration."
    info "Should be a readonly user (safe — cannot make changes)."
    echo

    prompt TACACS_TEST_USER "TACACS+ test username" "${TACACS_TEST_USER:-htc-ro}"
    if [[ -z "${TACACS_TEST_USER:-}" ]]; then die "Aborted: TACACS+ test username is required and cannot be empty. It is used to verify authentication after migration."; fi

    prompt_secret TACACS_TEST_PASS "TACACS+ test user password"
    TACACS_TEST_PASS="${TACACS_TEST_PASS:-}"

    if [[ -z "${TACACS_TEST_PASS:-}" ]]; then
        warn "No test password entered — TACACS+ verification step (step 5) will be skipped."
    else
        ok "Test user configured: ${TACACS_TEST_USER}"
    fi
}

# =============================================================
# SSH-BROKER CONFIGURATION
# =============================================================

configure_broker() {
    header "Configure ssh-broker safety session"
    info "ssh-broker provides a persistent SSH safety session for rollback."
    info "It must be running on this controller before migration starts."
    echo

    local default_url="${BROKER_URL:-http://127.0.0.1:8765}"
    prompt BROKER_URL   "ssh-broker URL"       "$default_url"
    prompt_secret BROKER_TOKEN "ssh-broker API token"

    if [[ -z "${BROKER_TOKEN:-}" ]]; then
        die "Aborted: broker API token is required and cannot be empty."
    fi

    # Verify broker is reachable
    echo
    if command -v curl &>/dev/null; then
        if curl -sf --max-time 3 "${BROKER_URL}/health" &>/dev/null; then
            ok "ssh-broker is reachable at ${BROKER_URL}"
        else
            warn "Could not reach ssh-broker at ${BROKER_URL}"
            warn "Make sure ssh-broker is running before executing the migration."
        fi
    fi

    ok "Broker settings configured."
}

# =============================================================
# VAULT CREATE / REKEY
# =============================================================

create_and_encrypt_vault() {
    local vf; vf="$(vault_file)"
    mkdir -p "$(dirname "$vf")"

    if [[ -f "$vf" ]]; then
        local backup="${vf}.bak.$(date +%Y%m%d%H%M%S)"
        mv "$vf" "$backup"
        info "Previous vault backed up: ${backup}"
    fi

    info "Writing vault.yml..."

    cat > "$vf" <<EOF
---
# vault.yml — TACACS+ migration secrets, encrypted with ansible-vault
# DO NOT commit this file to git
# To edit: ansible-vault edit ${VAULT_FILE_REL}
# To view: ansible-vault view ${VAULT_FILE_REL}

# ssh-broker safety session
broker_url:   "${BROKER_URL:-http://127.0.0.1:8765}"
broker_token: "${BROKER_TOKEN:-}"

# Local switch credentials (used by migration + rollback safety session)
local_user:          "${LOCAL_USER}"
local_pass:          "${LOCAL_PASS}"
local_enable:        "${LOCAL_ENABLE:-}"
local_admin_secret:  "${LOCAL_ADMIN_SECRET}"

# TACACS+ shared key — shared secret configured on your TACACS+ servers
tacacs_key: "${TACACS_KEY}"

# TACACS+ test user for verification after migration (readonly user)
tacacs_test_user: "${TACACS_TEST_USER}"
tacacs_test_pass: "${TACACS_TEST_PASS:-}"

# TACACS+ servers
tacacs_server_primary:   "${TACACS_SERVER_PRIMARY}"
tacacs_server_secondary: "${TACACS_SERVER_SECONDARY:-}"
EOF
    chmod 600 "$vf"
    _VAULT_GUARD="$vf"

    info "Encrypting vault.yml..."

    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        ansible-vault encrypt "$vf" \
            --vault-id "default@${VAULT_PASSWORD_FILE}" \
            --encrypt-vault-id default
    elif [[ -n "${VAULT_RAW_PASSWORD:-}" ]]; then
        printf '%s' "${VAULT_RAW_PASSWORD}" \
            | ansible-vault encrypt "$vf" \
                --vault-id "default@/dev/stdin" \
                --encrypt-vault-id default
    else
        ansible-vault encrypt "$vf" --encrypt-vault-id default
    fi

    _VAULT_GUARD=""
    ok "vault.yml encrypted."
}

do_configure_vault_password() {
    header "Change vault password"

    local vf; vf="$(vault_file)"
    [[ -f "$vf" ]] || die "vault.yml not found. Run 'configure-vault' first."

    info "You will need the CURRENT vault password, then set a NEW one."
    echo

    local cur_file="" cur_raw=""
    load_vars
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        info "Current vault password file: ${VAULT_PASSWORD_FILE}"
        if ! confirm "Use this file for current password?"; then
            prompt_secret cur_raw "Current vault password"
        else
            cur_file="${VAULT_PASSWORD_FILE}"
        fi
    else
        prompt_secret cur_raw "Current vault password"
    fi

    echo
    info "Now configure the NEW vault password:"
    VAULT_PASSWORD_FILE=""
    VAULT_RAW_PASSWORD=""
    _vault_password_manual

    local cur_args=()
    if [[ -n "$cur_file" ]]; then
        cur_args=(--vault-password-file "$cur_file")
    else
        cur_args=(--vault-password-file /dev/stdin)
    fi

    local new_args=()
    if [[ -n "${VAULT_PASSWORD_FILE:-}" ]]; then
        new_args=(--new-vault-password-file "${VAULT_PASSWORD_FILE}")
    else
        local tmp; tmp="$(mktemp)"
        printf '%s' "${VAULT_RAW_PASSWORD}" > "$tmp"
        chmod 600 "$tmp"
        new_args=(--new-vault-password-file "$tmp")
        trap "rm -f '$tmp'" RETURN
    fi

    if [[ -n "$cur_raw" ]]; then
        printf '%s' "$cur_raw" \
            | ansible-vault rekey "$vf" "${cur_args[@]}" "${new_args[@]}"
    else
        ansible-vault rekey "$vf" "${cur_args[@]}" "${new_args[@]}"
    fi

    ok "Vault password changed."
    save_vars
}

# =============================================================
# HOSTS CONFIGURATION
# =============================================================

configure_hosts() {
    header "Configure switch inventory"
    info "Add switches to migrate."
    info "Format: hostname IP (e.g. SW01 192.168.1.10)"
    info "IOS version is auto-detected during preflight — no grouping needed."
    echo

    local switches=""

    info "Enter one switch per line. Press Enter on empty line when done."
    info "Accepted formats: 'SW01 192.168.1.10' or just '192.168.1.10' (IP used as hostname)"
    while true; do
        echo -ne "  ${BOLD}[hostname] IP${NC} (empty to finish): "
        read -r line || _on_interrupt
        [[ -z "$line" ]] && break
        local hname hip
        hname="$(echo "$line" | awk '{print $1}')"
        hip="$(echo "$line" | awk '{print $2}')"
        if [[ -z "$hip" ]]; then
            # Only one token entered — treat it as IP, use IP as hostname
            hip="$hname"
            hname="$hip"
        fi
        switches+="${hname} ansible_host=${hip}"$'\n'
    done

    if [[ -z "$switches" ]]; then
        warn "No switches entered. Edit ${INSTALL_DIR}/inventory/hosts manually."
    fi

    _write_inventory "$switches"
}

_write_inventory() {
    local switches="$1"
    mkdir -p "${INSTALL_DIR}/inventory"

    {
        echo "# tacacs-migrate inventory"
        echo "# Generated by ${SCRIPT_NAME}"
        echo "# IOS version is auto-detected during preflight — no grouping needed."
        echo ""
        echo "[switches]"
        if [[ -n "$switches" ]]; then
            echo "$switches"
        else
            echo "# SW01 ansible_host=10.0.0.1"
            echo "# SW02 ansible_host=10.0.0.2"
        fi
        echo ""
        echo "[all:vars]"
        echo "ansible_user={{ local_user }}"
        echo "ansible_password={{ local_pass }}"
    } > "${INSTALL_DIR}/inventory/hosts"

    ok "Inventory written: ${INSTALL_DIR}/inventory/hosts"
}

_write_ansible_cfg() {
    local vault_line=""
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        vault_line="vault_password_file = ${VAULT_PASSWORD_FILE}"
    fi

    cat > "${INSTALL_DIR}/playbook/ansible.cfg" <<EOF
[defaults]
roles_path           = ../roles
inventory            = ../inventory/hosts
host_key_checking    = False
stdout_callback      = yaml
retry_files_enabled  = False
${vault_line}

[persistent_connection]
connect_timeout      = 30
command_timeout      = 60
EOF
    ok "ansible.cfg updated: ${INSTALL_DIR}/playbook/ansible.cfg"
}

# =============================================================
# FULL CONFIGURE
# =============================================================

configure_vault() {
    header "Configure TACACS+ migration secrets"
    load_vars

    local vf; vf="$(vault_file)"
    if [[ -f "$vf" ]]; then
        warn "An existing vault.yml was found. It will be replaced."
        if ! confirm "Continue?"; then info "Cancelled."; return; fi
    fi

    configure_broker
    configure_servers
    configure_switch_credentials
    configure_test_user
    configure_vault_password
    create_and_encrypt_vault
    _write_ansible_cfg
    save_vars

    echo
    ok "Vault configured and encrypted."
    if [[ -n "${TACACS_SERVER_SECONDARY:-}" ]]; then
        info "Servers: ${TACACS_SERVER_PRIMARY} (primary), ${TACACS_SERVER_SECONDARY} (secondary)"
    else
        info "Server:  ${TACACS_SERVER_PRIMARY} (single server mode)"
    fi
}

do_configure() {
    configure_hosts
    configure_vault
}

do_configure_broker() {
    header "Configure ssh-broker in vault"

    local vf; vf="$(vault_file)"
    [[ -f "$vf" ]] || die "vault.yml not found. Run 'configure-vault' first."

    load_vars

    # Decrypt vault to a temp file
    local tmp; tmp="$(mktemp)"
    chmod 600 "$tmp"
    _VAULT_GUARD="$tmp"

    local va=()
    mapfile -t va < <(vault_args)

    if [[ "${va[1]:-}" == "default@/dev/stdin" ]]; then
        vault_stdin_pipe | ansible-vault decrypt "$vf" "${va[@]}" --output "$tmp" \
            || die "Failed to decrypt vault.yml"
    else
        ansible-vault decrypt "$vf" "${va[@]}" --output "$tmp" \
            || die "Failed to decrypt vault.yml"
    fi

    configure_broker

    # Update broker_url and broker_token lines in the decrypted file.
    # If lines exist — replace them; if not — append broker section.
    if grep -q "^broker_url:" "$tmp" 2>/dev/null; then
        sed -i "s|^broker_url:.*|broker_url:   \"${BROKER_URL}\"|" "$tmp"
        sed -i "s|^broker_token:.*|broker_token: \"${BROKER_TOKEN}\"|" "$tmp"
    else
        printf '\n# ssh-broker safety session\nbroker_url:   "%s"\nbroker_token: "%s"\n' \
            "${BROKER_URL}" "${BROKER_TOKEN}" >> "$tmp"
    fi

    # Re-encrypt
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        ansible-vault encrypt "$tmp" \
            --vault-id "default@${VAULT_PASSWORD_FILE}" \
            --encrypt-vault-id default \
            --output "$vf"
    elif [[ -n "${VAULT_RAW_PASSWORD:-}" ]]; then
        printf '%s' "${VAULT_RAW_PASSWORD}" \
            | ansible-vault encrypt "$tmp" \
                --vault-id "default@/dev/stdin" \
                --encrypt-vault-id default \
                --output "$vf"
    else
        ansible-vault encrypt "$tmp" --encrypt-vault-id default --output "$vf"
    fi

    rm -f "$tmp"
    _VAULT_GUARD=""
    ok "Broker settings saved and vault re-encrypted."
    info "Verify with: ansible-vault view ${VAULT_FILE_REL}"
}

# =============================================================
# INSTALL
# =============================================================

do_install() {
    [[ "$MODE" == "source" ]] || die "install can only be run from the source directory."

    header "Installing ${PLAYBOOK_NAME}"
    check_dependencies || die "Dependency check failed."

    local default_loc; default_loc="$(detect_default_location)"
    prompt INSTALL_DIR "Install location" "$default_loc"
    export INSTALL_DIR

    if [[ -f "${INSTALL_DIR}/.installed" ]]; then
        warn "Already installed at: ${INSTALL_DIR}"
        if ! confirm "Reinstall (overwrite)?"; then info "Aborted."; return; fi
    fi

    info "Copying playbook files to ${INSTALL_DIR}..."
    mkdir -p "${INSTALL_DIR}"

    cp -r "${SCRIPT_DIR}/playbook" "${INSTALL_DIR}/"
    cp -r "${SCRIPT_DIR}/roles"    "${INSTALL_DIR}/"
    mkdir -p "${INSTALL_DIR}/inventory"
    cp "${SCRIPT_DIR}/inventory/hosts" "${INSTALL_DIR}/inventory/hosts"

    # Remove vault.yml if it was accidentally included
    rm -f "${INSTALL_DIR}/${VAULT_FILE_REL}"

    ok "Files copied."

    cp "${BASH_SOURCE[0]}" "${INSTALL_DIR}/tacacs-migrate.sh"
    chmod +x "${INSTALL_DIR}/tacacs-migrate.sh"
    ok "Management script installed: ${INSTALL_DIR}/tacacs-migrate.sh"

    [[ -f "${SCRIPT_DIR}/USAGE.md" ]] && cp "${SCRIPT_DIR}/USAGE.md" "${INSTALL_DIR}/USAGE.md"

    MODE="installed"
    INSTALL_DIR="${INSTALL_DIR}"
    touch "${INSTALL_DIR}/.installed"

    do_configure

    echo
    ok "Installation complete."
    echo
    info "Manage your deployment:"
    echo -e "  ${CYAN}${INSTALL_DIR}/tacacs-migrate.sh${NC}                — interactive menu"
    echo -e "  ${CYAN}${INSTALL_DIR}/tacacs-migrate.sh run${NC}             — run migration"
    echo -e "  ${CYAN}${INSTALL_DIR}/tacacs-migrate.sh run -l SW01${NC}     — migrate single switch"
    echo -e "  ${CYAN}${INSTALL_DIR}/tacacs-migrate.sh configure${NC}       — reconfigure"
    echo
}

# =============================================================
# RUN
# =============================================================

do_run() {
    header "Running migration playbook"

    [[ -f "${INSTALL_DIR}/.installed" ]] || die "Not installed. Run: $0 install"

    load_vars

    local vf; vf="$(vault_file)"
    [[ -f "$vf" ]] || die "vault.yml not found. Run: $0 configure-vault"

    # ssh-broker pre-flight check
    local _broker_url="${BROKER_URL:-http://127.0.0.1:8765}"
    if command -v curl &>/dev/null; then
        if curl -sf --max-time 2 "${_broker_url}/health" &>/dev/null; then
            ok "ssh-broker: reachable at ${_broker_url}"
        else
            warn "ssh-broker is NOT reachable at ${_broker_url}"
            warn "Migration will abort per-host at phase 0 (broker open)."
            warn "Start ssh-broker or configure broker settings: $0 configure-broker"
            echo
            if ! confirm "Continue anyway?"; then info "Aborted."; return; fi
        fi
    fi

    local va=()
    mapfile -t va < <(vault_args)

    local extra_args=()

    info "ansible-playbook migrate.yml ${va[*]:-} ${extra_args[*]:-} ${EXTRA_ARGS[*]:-}"
    cd "${INSTALL_DIR}/playbook"

    if [[ "${va[1]:-}" == "default@/dev/stdin" ]]; then
        vault_stdin_pipe | ansible-playbook migrate.yml \
            "${va[@]}" "${extra_args[@]}" "${EXTRA_ARGS[@]}"
    else
        ansible-playbook migrate.yml \
            "${va[@]}" "${extra_args[@]}" "${EXTRA_ARGS[@]}"
    fi
}

# =============================================================
# STATUS
# =============================================================

show_status() {
    header "Status"

    if [[ "$MODE" == "source" ]]; then
        info "Running in SOURCE mode: ${SCRIPT_DIR}"
        if [[ -f "${INSTALL_DIR}/.installed" ]]; then
            ok "Installed at: ${INSTALL_DIR}"
        else
            warn "Not installed. Run: $0 install"
        fi
        return
    fi

    ok "Install dir: ${INSTALL_DIR}"
    echo

    local vf; vf="$(vars_file)"
    if [[ -f "$vf" ]]; then
        load_vars
        echo -e "  ${BOLD}Vault pass file${NC} : ${VAULT_PASSWORD_FILE:-(will prompt)}"
    else
        warn "Not configured. Run: $0 configure"
    fi

    echo
    local inv="${INSTALL_DIR}/inventory/hosts"
    if [[ -f "$inv" ]]; then
        local sw_count
        sw_count="$(grep -cE '^[A-Za-z].*ansible_host=' "$inv" 2>/dev/null || echo 0)"
        ok "Inventory : ${sw_count} switch(es)"
        # Show non-commented hosts
        grep -E '^[A-Za-z].*ansible_host=' "$inv" 2>/dev/null | \
            sed 's/^/    /' || true
    else
        warn "Inventory not found — run: $0 configure-hosts"
    fi

    echo
    local vault_f; vault_f="$(vault_file)"
    if [[ -f "$vault_f" ]]; then
        if head -1 "$vault_f" 2>/dev/null | grep -q '^\$ANSIBLE_VAULT'; then
            ok "vault.yml : encrypted"
            # Show server config from vault (view without decrypting beyond header)
            info "To view vault contents: ansible-vault view ${VAULT_FILE_REL}"
        else
            warn "vault.yml : EXISTS BUT NOT ENCRYPTED — run: $0 configure-vault"
        fi
    else
        warn "vault.yml : not found — run: $0 configure-vault"
    fi
}

# =============================================================
# UNINSTALL
# =============================================================

do_uninstall() {
    header "Uninstalling ${PLAYBOOK_NAME}"
    [[ -f "${INSTALL_DIR}/.installed" ]] || { warn "Not installed."; return; }
    warn "This will permanently remove: ${INSTALL_DIR}"
    if ! confirm "Are you sure?"; then info "Aborted."; return; fi
    rm -rf "${INSTALL_DIR}"
    ok "Removed: ${INSTALL_DIR}"
}

# =============================================================
# MENUS
# =============================================================

menu_source() {
    while true; do
        echo
        echo -e "${BOLD}=== tacacs-migrate Installer ===${NC}"
        echo -e "  Source: ${CYAN}${SCRIPT_DIR}${NC}"
        echo -e "  Install target: ${CYAN}${INSTALL_DIR}${NC}"
        echo
        echo "  1) Install"
        echo "  2) Status"
        echo "  3) Exit"
        echo
        echo -ne "Choice [1-3]: "
        read -r choice || _on_interrupt
        case "$choice" in
            1) do_install; exit 0 ;;
            2) show_status ;;
            3) exit 0 ;;
            *) warn "Invalid choice." ;;
        esac
    done
}

menu_installed() {
    while true; do
        echo
        echo -e "${BOLD}=== tacacs-migrate Management ===${NC}"
        echo -e "  ${CYAN}${INSTALL_DIR}${NC}"
        echo
        echo "  1) Run migration playbook"
        echo "  2) Configure everything (hosts + vault)"
        echo "  3) Configure switches (inventory) only"
        echo "  4) Configure TACACS+ secrets only (recreate vault)"
        echo "  5) Configure ssh-broker settings (update vault)"
        echo "  6) Change vault password"
        echo "  7) Status"
        echo "  8) Uninstall"
        echo "  9) Exit"
        echo
        echo -ne "Choice [1-9]: "
        read -r choice || _on_interrupt
        case "$choice" in
            1) do_run ;;
            2) do_configure ;;
            3) configure_hosts ;;
            4) configure_vault ;;
            5) do_configure_broker ;;
            6) do_configure_vault_password ;;
            7) show_status ;;
            8) do_uninstall ;;
            9) exit 0 ;;
            *) warn "Invalid choice." ;;
        esac
    done
}

# =============================================================
# MAIN
# =============================================================

EXTRA_ARGS=()
ACTION="${1:-menu}"
shift || true
EXTRA_ARGS=("$@")

case "$ACTION" in
    install)
        do_install
        ;;
    configure)
        [[ "$MODE" == "installed" ]] || die "'configure' requires installed mode. Run install first."
        do_configure
        ;;
    configure-hosts)
        [[ "$MODE" == "installed" ]] || die "'configure-hosts' requires installed mode."
        configure_hosts
        ;;
    configure-vault)
        [[ "$MODE" == "installed" ]] || die "'configure-vault' requires installed mode."
        configure_vault
        ;;
    configure-broker)
        [[ "$MODE" == "installed" ]] || die "'configure-broker' requires installed mode."
        load_vars
        do_configure_broker
        ;;
    configure-vault-password)
        [[ "$MODE" == "installed" ]] || die "'configure-vault-password' requires installed mode."
        do_configure_vault_password
        ;;
    run)
        do_run
        ;;
    status)
        show_status
        ;;
    uninstall)
        do_uninstall
        ;;
    menu)
        if [[ "$MODE" == "source" ]]; then
            menu_source
        else
            menu_installed
        fi
        ;;
    help|--help|-h)
        echo
        echo -e "${BOLD}Usage:${NC} $0 <command> [args]"
        echo
        if [[ "$MODE" == "source" ]]; then
            echo "  install                    Install playbook to target directory"
            echo "  status                     Show installation status"
        else
            echo "  configure                  Configure hosts + secrets (full setup)"
            echo "  configure-hosts            Configure switch inventory only"
            echo "  configure-vault            Configure TACACS+ secrets (recreate vault)"
            echo "  configure-broker           Configure ssh-broker URL and token (update vault)"
            echo "  configure-vault-password   Change vault encryption password"
            echo "  run [--limit HOST] [args]  Run migration playbook"
            echo "  status                     Show current configuration"
            echo "  uninstall                  Remove installed playbook"
        fi
        echo "  help                       Show this message"
        echo
        echo -e "Current mode: ${CYAN}${MODE}${NC}  |  Install dir: ${CYAN}${INSTALL_DIR}${NC}"
        echo
        echo -e "${BOLD}Run examples:${NC}"
        echo "  $0 run                        — migrate all switches (serial=1)"
        echo "  $0 run -l AA01ASWI            — migrate single switch"
        echo "  $0 run -e serial=5            — migrate 5 switches in parallel"
        echo "  $0 run --tags step1,step2     — run specific steps only"
        echo
        ;;
    *)
        error "Unknown command: ${ACTION}"
        echo "Run '$0 help' for usage."
        exit 1
        ;;
esac
