#!/usr/bin/env bash
# =============================================================
# install.sh / tacacs-ng.sh — Installer & manager for tacacs-ng
# =============================================================
# Two operating modes detected automatically:
#
#   SOURCE mode  — run from the cloned repository (roles/ present)
#                  Commands: install, status, help
#
#   INSTALLED mode — run from the installed playbook directory
#                    (.installed marker present, or copied as tacacs-ng.sh)
#                    Commands: configure, configure-host, configure-users,
#                              configure-vault-password, run, status,
#                              uninstall, help
#
# On install, this script copies itself to INSTALL_DIR/tacacs-ng.sh
# so the user can manage the deployment from there without the source repo.
# =============================================================
set -euo pipefail

# ---------- colours ------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

# ---------- paths --------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
PLAYBOOK_NAME="tacacs-ng"
VAULT_FILE_REL="roles/tac_plus_ng_deploy/vars/vault.yml"

# ---------- helpers ------------------------------------------
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()      { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()     { error "$*"; exit 1; }
header()  { echo -e "\n${BOLD}=== $* ===${NC}"; }
prompt() {
    local var="$1" desc="$2" default="${3:-}"
    local input
    if [[ -n "$default" ]]; then
        echo -ne "${BOLD}${desc}${NC} [${default}]: "
    else
        echo -ne "${BOLD}${desc}${NC}: "
    fi
    read -r input || { echo; _on_interrupt; }
    [[ -z "$input" && -n "$default" ]] && input="$default"
    printf -v "$var" '%s' "$input"
}

prompt_secret() {
    local var="$1" desc="$2"
    local input
    echo -ne "${BOLD}${desc}${NC} (hidden): "
    read -rs input || { echo; _on_interrupt; }
    echo
    printf -v "$var" '%s' "$input"
}

confirm() {
    echo -ne "${BOLD}${1}${NC} [y/N]: "
    local r
    read -r r || { echo; _on_interrupt; }
    if [[ "$r" =~ ^[Yy]$ ]]; then return 0; else return 1; fi
}

# ---------- mode detection -----------------------------------
detect_mode() {
    if [[ -f "${SCRIPT_DIR}/.installed" ]]; then
        echo "installed"
    elif [[ -d "${SCRIPT_DIR}/roles" ]]; then
        echo "source"
    else
        echo "installed"   # fallback: assume deployed context
    fi
}

detect_default_location() {
    if [[ $EUID -eq 0 ]]; then
        echo "/etc/ansible/playbooks/${PLAYBOOK_NAME}"
    else
        echo "${HOME}/.ansible/playbooks/${PLAYBOOK_NAME}"
    fi
}

MODE="$(detect_mode)"

if [[ "$MODE" == "installed" ]]; then
    INSTALL_DIR="${SCRIPT_DIR}"
else
    INSTALL_DIR="${INSTALL_DIR:-$(detect_default_location)}"
fi

# ---------- path helpers -------------------------------------
vars_file()  { echo "${INSTALL_DIR}/vars.env"; }
vault_file() { echo "${INSTALL_DIR}/${VAULT_FILE_REL}"; }

# ---------- vault security — cleanup unencrypted file --------
_VAULT_GUARD=""   # set to vault path while it may be plaintext

_vault_cleanup() {
    if [[ -n "$_VAULT_GUARD" && -f "$_VAULT_GUARD" ]]; then
        if ! head -1 "$_VAULT_GUARD" 2>/dev/null | grep -q '^\$ANSIBLE_VAULT'; then
            warn "Removing unencrypted vault.yml (interrupted operation)"
            if command -v shred &>/dev/null; then
                shred -uz "$_VAULT_GUARD" 2>/dev/null || rm -f "$_VAULT_GUARD"
            else
                rm -f "$_VAULT_GUARD"
            fi
        fi
    fi
}

_on_interrupt() {
    echo  # newline after ^C on terminal
    info "Interrupted."
    exit 130
}

# EXIT runs _vault_cleanup (covers all exit paths including INT/TERM)
# INT/TERM call _on_interrupt which triggers exit → EXIT fires cleanup
trap '_vault_cleanup' EXIT
trap '_on_interrupt'  INT TERM HUP

# ---------- load / save vars ---------------------------------
load_vars() {
    local vf; vf="$(vars_file)"
    [[ -f "$vf" ]] && source "$vf" || true  # shellcheck disable=SC1090
}

save_vars() {
    local vf; vf="$(vars_file)"
    cat > "$vf" <<EOF
# tacacs-ng configuration — generated by ${SCRIPT_NAME}
# Do not commit to git

# --- Target host ---
ANSIBLE_TARGET_HOST="${ANSIBLE_TARGET_HOST:-}"
ANSIBLE_SSH_USER="${ANSIBLE_SSH_USER:-root}"
ANSIBLE_SSH_PORT="${ANSIBLE_SSH_PORT:-22}"
ANSIBLE_SSH_KEY="${ANSIBLE_SSH_KEY:-}"
ANSIBLE_BECOME="${ANSIBLE_BECOME:-false}"
ANSIBLE_BECOME_PASSWORD="${ANSIBLE_BECOME_PASSWORD:-}"

# --- Vault ---
VAULT_PASSWORD_FILE="${VAULT_PASSWORD_FILE:-}"

# --- TACACS+ functional test ---
TACACS_RO_PASSWORD="${TACACS_RO_PASSWORD:-}"
EOF
    chmod 600 "$vf"
    ok "Configuration saved: $vf"
}

# ---------- dependency check ---------------------------------
check_dependencies() {
    header "Checking dependencies"
    local all_ok=true

    for cmd_desc in \
        "ansible-playbook:ansible-playbook (apt install ansible)" \
        "ansible-vault:ansible-vault (part of ansible)" \
        "python3:python3 (apt install python3)" \
        "openssl:openssl (apt install openssl)"; do
        local cmd="${cmd_desc%%:*}"
        local desc="${cmd_desc#*:}"
        if command -v "$cmd" &>/dev/null; then
            ok "${cmd}: found"
        else
            error "${cmd} not found — install: ${desc}"
            all_ok=false
        fi
    done

    if ansible-galaxy collection list 2>/dev/null | grep -q "community.general"; then
        ok "community.general: present"
    else
        warn "community.general not found — installing..."
        if ansible-galaxy collection install community.general; then
            ok "community.general: installed"
        else
            error "Failed to install community.general"
            all_ok=false
        fi
    fi

    [[ "$all_ok" == true ]]
}

# =============================================================
# VAULT PASSWORD
# =============================================================

find_vault_password_files() {
    # Returns list of existing vault password files, deduplicated
    local candidates=()

    # 1. Already configured in vars.env
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        candidates+=("${VAULT_PASSWORD_FILE}")
    fi

    # 2. From ansible.cfg files (playbook-local, user, system)
    local cfgs=(
        "${INSTALL_DIR}/playbook/ansible.cfg"
        "${HOME}/.ansible.cfg"
        "/etc/ansible/ansible.cfg"
    )
    for cfg in "${cfgs[@]}"; do
        if [[ -f "$cfg" ]]; then
            local cfg_vp
            cfg_vp="$(grep -E '^\s*vault_password_file\s*=' "$cfg" 2>/dev/null \
                      | sed 's/.*=\s*//' | tr -d ' \t' | head -1 || true)"
            cfg_vp="${cfg_vp/#\~/$HOME}"
            [[ -n "$cfg_vp" && -f "$cfg_vp" ]] && candidates+=("$cfg_vp")
        fi
    done

    # 3. Common locations
    local common=(
        "${HOME}/.ansible/vault_pass"
        "${HOME}/.ansible/vault_password"
        "${HOME}/.vault_pass"
        "${HOME}/.vault_password"
        "/etc/ansible/vault/.vault_pass"
        "/etc/ansible/vault/vault_pass"
    )
    for f in "${common[@]}"; do
        [[ -f "$f" ]] && candidates+=("$f")
    done

    # Deduplicate preserving order
    local seen=()
    for f in "${candidates[@]:-}"; do
        local dup=false
        for s in "${seen[@]:-}"; do [[ "$s" == "$f" ]] && dup=true && break; done
        [[ "$dup" == false ]] && seen+=("$f")
    done

    printf '%s\n' "${seen[@]:-}"
}

# Sets globals: VAULT_PASSWORD_FILE (path or empty), VAULT_RAW_PASSWORD (if manual, no file)
configure_vault_password() {
    header "Vault password"
    info "The vault password will be used to encrypt vault.yml."
    echo

    VAULT_RAW_PASSWORD=""

    # Collect all known candidates
    local candidates=()
    while IFS= read -r line; do
        [[ -n "$line" ]] && candidates+=("$line")
    done < <(find_vault_password_files)

    # Build menu
    local options=()
    local i=1

    if [[ ${#candidates[@]} -gt 0 ]]; then
        for f in "${candidates[@]}"; do
            echo -e "  ${BOLD}${i})${NC} Use existing file: ${CYAN}${f}${NC}"
            options+=("$f")
            i=$(( i + 1 ))
        done
        echo
    fi

    echo -e "  ${BOLD}${i})${NC} Specify a different file path"
    options+=("__custom_path__")
    i=$(( i + 1 ))
    echo -e "  ${BOLD}${i})${NC} Enter password manually (offer to save to file)"
    options+=("__manual__")
    local max=$i

    echo
    local choice idx selected
    while true; do
        echo -ne "Choice [1-${max}]: "
        read -r choice || _on_interrupt
        # Validate: must be a number in range
        if [[ "$choice" =~ ^[0-9]+$ ]]; then
            idx=$(( choice - 1 ))
            if [[ $idx -ge 0 && $idx -lt ${#options[@]} ]]; then break; fi
        fi
        warn "Please enter a number between 1 and ${max}."
    done

    selected="${options[$idx]}"

    case "$selected" in
        __custom_path__)
            local default_path="${HOME}/.ansible/vault_pass"
            prompt VAULT_PASSWORD_FILE "Path to vault password file" "$default_path"
            VAULT_PASSWORD_FILE="${VAULT_PASSWORD_FILE/#\~/$HOME}"
            if [[ ! -f "$VAULT_PASSWORD_FILE" ]]; then
                warn "File not found: ${VAULT_PASSWORD_FILE}"
                warn "Ensure the file exists and contains the vault password before running."
            else
                ok "Will use: ${VAULT_PASSWORD_FILE}"
            fi
            ;;
        __manual__)
            _vault_password_manual
            ;;
        *)
            # Existing file selected
            if [[ ! -f "$selected" ]]; then
                die "Vault password file not found: '${selected}'"
            fi
            VAULT_PASSWORD_FILE="$selected"
            ok "Will use: ${VAULT_PASSWORD_FILE}"
            ;;
    esac
}

_vault_password_manual() {
    local pw pw2
    while true; do
        prompt_secret pw "Enter vault password"
        [[ -z "$pw" ]] && { warn "Password cannot be empty."; continue; }
        prompt_secret pw2 "Confirm vault password"
        [[ "$pw" == "$pw2" ]] && break
        warn "Passwords do not match. Try again."
    done
    VAULT_RAW_PASSWORD="$pw"

    echo
    warn "IMPORTANT: If you lose the vault password, secrets cannot be recovered."
    echo
    if confirm "Save password to a file for future use?"; then
        local default_path="${HOME}/.ansible/vault_pass"
        prompt VAULT_PASSWORD_FILE "Path to save password file" "$default_path"
        VAULT_PASSWORD_FILE="${VAULT_PASSWORD_FILE/#\~/$HOME}"
        mkdir -p "$(dirname "$VAULT_PASSWORD_FILE")"
        printf '%s' "$pw" > "$VAULT_PASSWORD_FILE"
        chmod 600 "$VAULT_PASSWORD_FILE"
        ok "Password saved: ${VAULT_PASSWORD_FILE}"
        warn "Back up this file to a password manager."
        VAULT_RAW_PASSWORD=""  # no longer needed, file takes precedence
    else
        VAULT_PASSWORD_FILE=""
        warn "No file saved — you will be prompted for the password on every run."
    fi
}

# Resolve vault pass args for ansible-playbook
vault_args() {
    # Use --vault-id to explicitly name the identity and avoid conflicts
    # with system-level ansible.cfg that may define its own vault passwords.
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        printf '%s\n' "--vault-id" "default@${VAULT_PASSWORD_FILE}"
    elif [[ -n "${VAULT_RAW_PASSWORD:-}" ]]; then
        printf '%s\n' "--vault-id" "default@/dev/stdin"
    else
        printf '%s\n' "--ask-vault-pass"
    fi
}

# Pipe vault password to stdin if needed
vault_stdin_pipe() {
    if [[ -n "${VAULT_RAW_PASSWORD:-}" ]]; then
        printf '%s' "${VAULT_RAW_PASSWORD}"
    fi
}

# =============================================================
# TACACS+ USERS
# =============================================================

VALID_ROLES="admin engineer readonly helpdesk"

_prompt_single_user() {
    local idx="$1"
    echo
    echo -e "${BOLD}-- User #${idx} --${NC}"
    echo -e "  Roles: ${CYAN}${VALID_ROLES}${NC}"

    while true; do
        prompt U_NAME   "  Username"
        [[ -n "$U_NAME" ]] && break
        warn "Username cannot be empty."
    done

    while true; do
        echo -ne "  ${BOLD}Role${NC}: "
        read -r U_ROLE || _on_interrupt
        local valid=false
        for r in $VALID_ROLES; do [[ "$r" == "$U_ROLE" ]] && valid=true; done
        [[ "$valid" == true ]] && break
        warn "  Invalid role. Choose from: ${VALID_ROLES}"
    done

    local pw pw2
    while true; do
        prompt_secret pw "  Password for ${U_NAME}"
        [[ -z "$pw" ]] && { warn "Password cannot be empty."; continue; }
        prompt_secret pw2 "  Confirm password"
        [[ "$pw" == "$pw2" ]] && break
        warn "  Passwords do not match."
    done

    U_HASH="$(openssl passwd -6 "$pw")"
    ok "  Hash generated for ${U_NAME} (SHA-512)"
}

configure_users() {
    header "TACACS+ users"
    info "Define users for local TACACS+ authentication."
    info "  admin    — priv 15, all commands"
    info "  engineer — priv 10, limited commands (no reload/delete/erase/debug)"
    info "  readonly — show commands only"
    info "  helpdesk — L1/L2 diagnostics (show interfaces/mac/arp/cdp/vlan + ping)"
    echo

    TACACS_USERS_YAML=""
    local count=0

    while true; do
        local U_NAME="" U_ROLE="" U_HASH=""
        _prompt_single_user $(( count + 1 ))
        count=$(( count + 1 ))

        TACACS_USERS_YAML+="  - name: ${U_NAME}
    role: ${U_ROLE}
    password_hash: \"${U_HASH}\"
"
        echo
        if ! confirm "Add another user?"; then break; fi
    done

    ok "${count} user(s) configured."

    # Determine test user: first 'readonly', else first user
    TACACS_TEST_USER=""
    local cur_name=""
    while IFS= read -r line; do
        if [[ "$line" =~ ^[[:space:]]*-\ name:\ (.+)$ ]]; then
            cur_name="${BASH_REMATCH[1]}"
        fi
        if [[ "$line" =~ ^[[:space:]]*role:\ readonly$ && -z "$TACACS_TEST_USER" ]]; then
            TACACS_TEST_USER="$cur_name"
        fi
    done <<< "$TACACS_USERS_YAML"

    if [[ -z "$TACACS_TEST_USER" ]]; then
        # Fall back to first user in the list (pure bash, no grep)
        while IFS= read -r line; do
            if [[ "$line" =~ ^[[:space:]]*-\ name:\ (.+)$ ]]; then
                TACACS_TEST_USER="${BASH_REMATCH[1]}"
                break
            fi
        done <<< "$TACACS_USERS_YAML"
    fi
}

# =============================================================
# VAULT CREATE / REKEY
# =============================================================

create_and_encrypt_vault() {
    local vf; vf="$(vault_file)"
    mkdir -p "$(dirname "$vf")"

    # If old vault exists — back it up before overwriting
    if [[ -f "$vf" ]]; then
        local backup="${vf}.bak.$(date +%Y%m%d%H%M%S)"
        mv "$vf" "$backup"
        info "Previous vault backed up: ${backup}"
    fi

    info "Writing vault.yml..."
    # Build optional become_password line
    local become_line=""
    [[ -n "${ANSIBLE_BECOME_PASSWORD:-}" ]] && \
        become_line=$'\n'"# Sudo password for ansible become"$'\n'"ansible_become_password: \"${ANSIBLE_BECOME_PASSWORD}\""

    cat > "$vf" <<EOF
---
# vault.yml — TACACS+ secrets, encrypted with ansible-vault
# DO NOT commit this file to git (it is in .gitignore)
# To edit: ansible-vault edit ${VAULT_FILE_REL}
# To view: ansible-vault view ${VAULT_FILE_REL}

# TACACS+ shared secret — must match 'key' on all network devices
tacacs_server_key: "${TACACS_SERVER_KEY}"

# Local users for TACACS+ authentication
tacacs_users:
${TACACS_USERS_YAML}${become_line}
EOF
    chmod 600 "$vf"
    _VAULT_GUARD="$vf"   # arm cleanup trap

    info "Encrypting vault.yml..."

    # Always pass the vault identity explicitly to avoid conflicts with
    # system-level ansible.cfg that may define its own vault_password_file.
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        ansible-vault encrypt "$vf" \
            --vault-id "default@${VAULT_PASSWORD_FILE}" \
            --encrypt-vault-id default
    elif [[ -n "${VAULT_RAW_PASSWORD:-}" ]]; then
        printf '%s' "${VAULT_RAW_PASSWORD}" \
            | ansible-vault encrypt "$vf" \
                --vault-id "default@/dev/stdin" \
                --encrypt-vault-id default
    else
        # Last resort: interactive prompt
        ansible-vault encrypt "$vf" --encrypt-vault-id default
    fi

    _VAULT_GUARD=""   # disarm — file is now encrypted
    ok "vault.yml encrypted."
}

do_configure_vault_password() {
    # Rekey existing vault with a new password
    header "Change vault password"

    local vf; vf="$(vault_file)"
    [[ -f "$vf" ]] || die "vault.yml not found. Run 'configure-users' first."

    info "You will need the CURRENT vault password, then set a NEW one."
    echo

    # Current password
    local cur_file="" cur_raw=""
    load_vars
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        info "Current vault password file: ${VAULT_PASSWORD_FILE}"
        if ! confirm "Use this file for current password?"; then
            prompt_secret cur_raw "Current vault password"
        else
            cur_file="${VAULT_PASSWORD_FILE}"
        fi
    else
        prompt_secret cur_raw "Current vault password"
    fi

    # New password
    echo
    info "Now configure the NEW vault password:"
    VAULT_PASSWORD_FILE=""
    VAULT_RAW_PASSWORD=""
    _vault_password_manual

    # Perform rekey
    local cur_args=()
    if [[ -n "$cur_file" ]]; then
        cur_args=(--vault-password-file "$cur_file")
    else
        cur_args=(--vault-password-file /dev/stdin)
    fi

    local new_args=()
    if [[ -n "${VAULT_PASSWORD_FILE:-}" ]]; then
        new_args=(--new-vault-password-file "${VAULT_PASSWORD_FILE}")
    else
        # Write new password to a temp file for rekey, then remove
        local tmp; tmp="$(mktemp)"
        printf '%s' "${VAULT_RAW_PASSWORD}" > "$tmp"
        chmod 600 "$tmp"
        new_args=(--new-vault-password-file "$tmp")
        trap "rm -f '$tmp'" RETURN
    fi

    if [[ -n "$cur_raw" ]]; then
        printf '%s' "$cur_raw" \
            | ansible-vault rekey "$vf" "${cur_args[@]}" "${new_args[@]}"
    else
        ansible-vault rekey "$vf" "${cur_args[@]}" "${new_args[@]}"
    fi

    ok "Vault password changed."
    save_vars
}

# =============================================================
# CONFIGURE SECTIONS
# =============================================================

configure_host() {
    header "Configure target host"
    load_vars
    info "Press Enter to keep current value (shown in brackets)."
    echo

    echo -e "${BOLD}-- SSH / Target host --${NC}"

    prompt ANSIBLE_TARGET_HOST "Target host IP or hostname" "${ANSIBLE_TARGET_HOST:-}"
    [[ -z "${ANSIBLE_TARGET_HOST:-}" ]] && die "Target host is required."

    prompt ANSIBLE_SSH_USER "SSH user" "${ANSIBLE_SSH_USER:-root}"
    prompt ANSIBLE_SSH_PORT "SSH port" "${ANSIBLE_SSH_PORT:-22}"

    local default_key="${ANSIBLE_SSH_KEY:-${HOME}/.ssh/id_rsa}"
    prompt ANSIBLE_SSH_KEY \
        "Path to SSH private key (leave empty for password auth)" \
        "${default_key}"
    if [[ -n "${ANSIBLE_SSH_KEY:-}" && ! -f "${ANSIBLE_SSH_KEY}" ]]; then
        warn "Key file not found: ${ANSIBLE_SSH_KEY} — ensure it exists before running."
    fi

    if [[ "${ANSIBLE_SSH_USER}" != "root" ]]; then
        echo -ne "${BOLD}Use sudo (become) on target?${NC} [${ANSIBLE_BECOME:-false}] (true/false): "
        read -r _become || _on_interrupt
        ANSIBLE_BECOME="${_become:-${ANSIBLE_BECOME:-false}}"

        if [[ "${ANSIBLE_BECOME}" == "true" ]]; then
            echo
            echo -e "${BOLD}-- Sudo password --${NC}"
            info "The sudo password will be stored encrypted in vault.yml."
            local cur_indicator=""
            [[ -n "${ANSIBLE_BECOME_PASSWORD:-}" ]] && cur_indicator=" (currently set)"
            echo -ne "${BOLD}Sudo password for ${ANSIBLE_SSH_USER}${NC}${cur_indicator} (leave empty to keep current): "
            local _bp
            read -rs _bp || _on_interrupt; echo
            [[ -n "$_bp" ]] && ANSIBLE_BECOME_PASSWORD="$_bp"
        else
            ANSIBLE_BECOME_PASSWORD=""
        fi
    else
        ANSIBLE_BECOME="false"
        ANSIBLE_BECOME_PASSWORD=""
    fi

    save_vars
    _write_inventory
}

_write_inventory() {
    mkdir -p "${INSTALL_DIR}/inventory"

    {
        echo "[tacacs_servers]"
        echo "tacacs01 ansible_host=${ANSIBLE_TARGET_HOST}"
        echo ""
        echo "[tacacs_servers:vars]"
        echo "ansible_user=${ANSIBLE_SSH_USER}"
        echo "ansible_port=${ANSIBLE_SSH_PORT}"
        [[ -n "${ANSIBLE_SSH_KEY:-}" ]] && echo "ansible_ssh_private_key_file=${ANSIBLE_SSH_KEY}"
        if [[ "${ANSIBLE_BECOME:-false}" == "true" ]]; then
            echo "ansible_become=true"
            # Password comes from vault variable ansible_become_password
            [[ -n "${ANSIBLE_BECOME_PASSWORD:-}" ]] && echo "ansible_become_pass={{ ansible_become_password }}"
        fi
    } > "${INSTALL_DIR}/inventory/tacacs-ng"

    ok "Inventory written: ${INSTALL_DIR}/inventory/tacacs-ng"
}

_write_ansible_cfg() {
    # Write playbook/ansible.cfg with vault_password_file if we have one.
    # This ensures ansible-playbook finds the vault password regardless of
    # the working directory or system-level ansible.cfg.
    local vault_line=""
    if [[ -n "${VAULT_PASSWORD_FILE:-}" && -f "${VAULT_PASSWORD_FILE}" ]]; then
        vault_line="vault_password_file = ${VAULT_PASSWORD_FILE}"
    fi

    cat > "${INSTALL_DIR}/playbook/ansible.cfg" <<EOF
[defaults]
roles_path    = ../roles
inventory     = ../inventory/tacacs-ng
${vault_line}
EOF
    ok "ansible.cfg updated: ${INSTALL_DIR}/playbook/ansible.cfg"
}

configure_users_and_vault() {
    header "Configure TACACS+ users"
    load_vars

    # Warn if vault already exists
    local vf; vf="$(vault_file)"
    if [[ -f "$vf" ]]; then
        warn "An existing vault.yml was found. It will be replaced."
        if ! confirm "Continue?"; then info "Cancelled."; return; fi
    fi

    echo
    echo -e "${BOLD}-- TACACS+ shared key --${NC}"
    prompt_secret TACACS_SERVER_KEY "TACACS+ shared key (used on all network devices)"
    [[ -z "${TACACS_SERVER_KEY:-}" ]] && die "TACACS+ shared key is required."

    echo
    echo -e "${BOLD}-- Functional test (optional) --${NC}"
    echo -ne "${BOLD}Test password${NC} (leave empty to skip auth test) [${TACACS_RO_PASSWORD:+(set)}]: "
    read -rs _pw || _on_interrupt; echo
    [[ -n "$_pw" ]] && TACACS_RO_PASSWORD="$_pw"

    configure_users
    configure_vault_password
    create_and_encrypt_vault
    _write_ansible_cfg
    save_vars

    echo
    ok "TACACS+ users configured and vault encrypted."
    info "Test user for functional test: ${TACACS_TEST_USER:-none}"
}

# Full configure: host + users
do_configure() {
    configure_host
    configure_users_and_vault
}

# =============================================================
# INSTALL
# =============================================================

do_install() {
    [[ "$MODE" == "source" ]] || die "install can only be run from the source directory."

    header "Installing ${PLAYBOOK_NAME}"
    check_dependencies || die "Dependency check failed."

    local default_loc; default_loc="$(detect_default_location)"
    prompt INSTALL_DIR "Install location" "$default_loc"
    export INSTALL_DIR

    if [[ -f "${INSTALL_DIR}/.installed" ]]; then
        warn "Already installed at: ${INSTALL_DIR}"
        if ! confirm "Reinstall (overwrite)?"; then info "Aborted."; return; fi
    fi

    info "Copying playbook files to ${INSTALL_DIR}..."
    mkdir -p "${INSTALL_DIR}"

    # Copy only what is needed — no install.sh, README, .gitignore, or loose files
    cp -r "${SCRIPT_DIR}/playbook" "${INSTALL_DIR}/"
    cp -r "${SCRIPT_DIR}/roles"    "${INSTALL_DIR}/"
    mkdir -p "${INSTALL_DIR}/inventory"

    # Remove files that must not be in the installed environment
    rm -f  "${INSTALL_DIR}/roles/tac_plus_ng_deploy/vars/vault.yml"
    rm -rf "${INSTALL_DIR}/roles/tac_plus_ng_deploy/files"

    ok "Files copied."

    # Copy this script as the management tool
    cp "${BASH_SOURCE[0]}" "${INSTALL_DIR}/tacacs-ng.sh"
    chmod +x "${INSTALL_DIR}/tacacs-ng.sh"
    ok "Management script installed: ${INSTALL_DIR}/tacacs-ng.sh"

    # Copy usage guide
    [[ -f "${SCRIPT_DIR}/USAGE.md" ]] && cp "${SCRIPT_DIR}/USAGE.md" "${INSTALL_DIR}/USAGE.md"

    # Switch to installed mode for configure
    MODE="installed"
    INSTALL_DIR="${INSTALL_DIR}"
    touch "${INSTALL_DIR}/.installed"

    do_configure

    echo
    ok "Installation complete."
    echo
    info "Manage your deployment:"
    echo -e "  ${CYAN}${INSTALL_DIR}/tacacs-ng.sh${NC}          — interactive menu"
    echo -e "  ${CYAN}${INSTALL_DIR}/tacacs-ng.sh run${NC}       — run playbook"
    echo -e "  ${CYAN}${INSTALL_DIR}/tacacs-ng.sh configure${NC}  — reconfigure"
    echo
}

# =============================================================
# RUN
# =============================================================

do_run() {
    header "Running playbook"

    [[ -f "${INSTALL_DIR}/.installed" ]] || die "Not installed. Run: $0 install"

    load_vars
    [[ -z "${ANSIBLE_TARGET_HOST:-}" ]] && die "Host not configured. Run: $0 configure-host"

    local vf; vf="$(vault_file)"
    [[ -f "$vf" ]] || die "vault.yml not found. Run: $0 configure-users"

    local va=()
    mapfile -t va < <(vault_args)

    local extra_args=()
    [[ -n "${TACACS_RO_PASSWORD:-}" ]] && extra_args+=(-e "tacacs_ro_password=${TACACS_RO_PASSWORD}")

    info "ansible-playbook deploy-tacacs.yml ${va[*]:-} ${extra_args[*]:-} ${EXTRA_ARGS[*]:-}"
    cd "${INSTALL_DIR}/playbook"

    if [[ "${va[1]:-}" == "default@/dev/stdin" ]]; then
        vault_stdin_pipe | ansible-playbook deploy-tacacs.yml \
            "${va[@]}" "${extra_args[@]}" "${EXTRA_ARGS[@]}"
    else
        ansible-playbook deploy-tacacs.yml \
            "${va[@]}" "${extra_args[@]}" "${EXTRA_ARGS[@]}"
    fi
}

# =============================================================
# STATUS
# =============================================================

show_status() {
    header "Status"

    if [[ "$MODE" == "source" ]]; then
        info "Running in SOURCE mode: ${SCRIPT_DIR}"
        if [[ -f "${INSTALL_DIR}/.installed" ]]; then
            ok "Installed at: ${INSTALL_DIR}"
        else
            warn "Not installed. Run: $0 install"
        fi
        return
    fi

    ok "Install dir: ${INSTALL_DIR}"
    echo

    local vf; vf="$(vars_file)"
    if [[ -f "$vf" ]]; then
        load_vars
        echo -e "  ${BOLD}Target host${NC}     : ${ANSIBLE_TARGET_HOST:-${RED}(not set)${NC}}"
        echo -e "  ${BOLD}SSH user${NC}        : ${ANSIBLE_SSH_USER:-root}"
        echo -e "  ${BOLD}SSH key${NC}         : ${ANSIBLE_SSH_KEY:-(password auth)}"
        echo -e "  ${BOLD}Vault pass file${NC} : ${VAULT_PASSWORD_FILE:-(will prompt)}"
        echo -e "  ${BOLD}Functional test${NC} : ${TACACS_RO_PASSWORD:+(password set)}"
        [[ -z "${TACACS_RO_PASSWORD:-}" ]] && \
            echo -e "               ${YELLOW}(skipped — set with configure-users)${NC}"
    else
        warn "Not configured. Run: $0 configure"
    fi

    echo
    local vault_f; vault_f="$(vault_file)"
    if [[ -f "$vault_f" ]]; then
        if head -1 "$vault_f" 2>/dev/null | grep -q '^\$ANSIBLE_VAULT'; then
            ok "vault.yml : encrypted"
        else
            warn "vault.yml : EXISTS BUT NOT ENCRYPTED — run: $0 configure-users"
        fi
    else
        warn "vault.yml : not found — run: $0 configure-users"
    fi
}

# =============================================================
# UNINSTALL
# =============================================================

do_uninstall() {
    header "Uninstalling ${PLAYBOOK_NAME}"
    [[ -f "${INSTALL_DIR}/.installed" ]] || { warn "Not installed."; return; }
    warn "This will permanently remove: ${INSTALL_DIR}"
    if ! confirm "Are you sure?"; then info "Aborted."; return; fi
    rm -rf "${INSTALL_DIR}"
    ok "Removed: ${INSTALL_DIR}"
}

# =============================================================
# MENUS
# =============================================================

menu_source() {
    while true; do
        echo
        echo -e "${BOLD}=== tacacs-ng Installer ===${NC}"
        echo -e "  Source: ${CYAN}${SCRIPT_DIR}${NC}"
        echo -e "  Install target: ${CYAN}${INSTALL_DIR}${NC}"
        echo
        echo "  1) Install"
        echo "  2) Status"
        echo "  3) Exit"
        echo
        echo -ne "Choice [1-3]: "
        read -r choice || _on_interrupt
        case "$choice" in
            1) do_install ;;
            2) show_status ;;
            3) exit 0 ;;
            *) warn "Invalid choice." ;;
        esac
    done
}

menu_installed() {
    while true; do
        echo
        echo -e "${BOLD}=== tacacs-ng Management ===${NC}"
        echo -e "  ${CYAN}${INSTALL_DIR}${NC}"
        echo
        echo "  1) Run playbook (deploy / update)"
        echo "  2) Configure everything (host + users)"
        echo "  3) Configure target host only"
        echo "  4) Configure TACACS+ users only (recreate vault)"
        echo "  5) Change vault password"
        echo "  6) Status"
        echo "  7) Uninstall"
        echo "  8) Exit"
        echo
        echo -ne "Choice [1-8]: "
        read -r choice || _on_interrupt
        case "$choice" in
            1) do_run ;;
            2) do_configure ;;
            3) configure_host ;;
            4) configure_users_and_vault ;;
            5) do_configure_vault_password ;;
            6) show_status ;;
            7) do_uninstall ;;
            8) exit 0 ;;
            *) warn "Invalid choice." ;;
        esac
    done
}

# =============================================================
# MAIN
# =============================================================

EXTRA_ARGS=()
ACTION="${1:-menu}"
shift || true
EXTRA_ARGS=("$@")

case "$ACTION" in
    install)
        do_install
        ;;
    configure)
        [[ "$MODE" == "installed" ]] || die "'configure' requires installed mode. Run install first."
        do_configure
        ;;
    configure-host)
        [[ "$MODE" == "installed" ]] || die "'configure-host' requires installed mode."
        configure_host
        ;;
    configure-users)
        [[ "$MODE" == "installed" ]] || die "'configure-users' requires installed mode."
        configure_users_and_vault
        ;;
    configure-vault-password)
        [[ "$MODE" == "installed" ]] || die "'configure-vault-password' requires installed mode."
        do_configure_vault_password
        ;;
    run)
        do_run
        ;;
    status)
        show_status
        ;;
    uninstall)
        do_uninstall
        ;;
    menu)
        if [[ "$MODE" == "source" ]]; then
            menu_source
        else
            menu_installed
        fi
        ;;
    help|--help|-h)
        echo
        echo -e "${BOLD}Usage:${NC} $0 <command> [args]"
        echo
        if [[ "$MODE" == "source" ]]; then
            echo "  install                    Install playbook to target directory"
            echo "  status                     Show installation status"
        else
            echo "  configure                  Configure host + TACACS+ users"
            echo "  configure-host             Configure target host / SSH only"
            echo "  configure-users            Configure TACACS+ users (recreate vault)"
            echo "  configure-vault-password   Change vault encryption password"
            echo "  run [--tags ...] [args]    Run Ansible playbook"
            echo "  status                     Show current configuration"
            echo "  uninstall                  Remove installed playbook"
        fi
        echo "  help                       Show this message"
        echo
        echo -e "Current mode: ${CYAN}${MODE}${NC}  |  Install dir: ${CYAN}${INSTALL_DIR}${NC}"
        echo
        ;;
    *)
        error "Unknown command: ${ACTION}"
        echo "Run '$0 help' for usage."
        exit 1
        ;;
esac
